### ISSUE TITLE
Discrete collision detection with GJK is broken when same object that shape is Rectangle or Cuboid are given

### ISSUE THREAD

**Issue by ix5231** [kvark/collision-rs#51]
- `rustc --version`: `rustc 1.21.0 (3b72af97e 2017-10-09)`
- OS: Windows 10 Pro 1709
- collision-rs version: master branch (`3cb6779`)

Issue
-----
- Rectangle: Can't detect collision.
- Cuboid: Cant't detect collision and `GJK::distance()` panics.

Code
----
```rust
use cgmath::{Basis2, Decomposed, Quaternion, Rad, Rotation2, Rotation3, Vector2, Vector3};
use collision::algorithm::minkowski::{GJK2, GJK3};
use collision::primitive::*;

fn transform(x: f32, y: f32, angle: f32) -> Decomposed<Vector2<f32>, Basis2<f32>> {
    Decomposed {
        disp: Vector2::new(x, y),
        rot: Rotation2::from_angle(Rad(angle)),
        scale: 1.,
    }
}
fn transform_3d(x: f32, y: f32, z: f32, angle_z: f32) -> Decomposed<Vector3<f32>, Quaternion<f32>> {
    Decomposed {
        disp: Vector3::new(x, y, z),
        rot: Quaternion::from_angle_z(Rad(angle_z)),
        scale: 1.,
    }
}

{
    let gjk = GJK2::new();
    let trans = &transform(0., 0., 0.);

    let shape = &Rectangle::new(10., 10.);
    println!("{:?}", gjk.intersect(shape, trans, shape, trans)); // None
    println!("{:?}", gjk.distance(shape, trans, shape, trans)); // None
}
{
    let gjk = GJK3::new();
    let trans = &transform_3d(0., 0., 0., 0.);

    let shape = &Cuboid::new(10., 10., 10.);
    println!("{:?}", gjk.intersect(shape, trans, shape, trans)); // None
    println!("{:?}", gjk.distance(shape, trans, shape, trans)); // thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
}
```

Continuous collision detection works properly.

By the way, I got
```
thread 'main' panicked at 'Simplex processing failed to deduce that this simplex [Vector3 [NaN, NaN, NaN], Vector3 [NaN, NaN, NaN], Vector3 [NaN, NaN, NaN]] is an edge case', C:\Users\Ix5231\.cargo\git\checkouts\collision-rs-2c62c906efffa0e5\3cb6779\src\algorithm\minkowski\gjk\simplex\simplex3d.rs:147:12
```
at `GJK::distance()` when I tried `Sphere`. Is it a bug?

**Comment by Rhuagh** [comment]
If you use the exact same shape Gjk will get divide by zero I guess. It's a bit difficult to get around so it's not being handled at all atm, so yes, you will have undefined results. It's quite rare you'll have exactly overlapping shapes with the same primitive.

**Comment by vitvakatu** [comment]
As for me, it seems pretty logical when there's no intersection between absolutely equal shapes from math side.

**Comment by Rhuagh** [comment]
This is an edge case, I think it occurs because all support points will be the origin.

**Comment by Rhuagh** [comment]
The problem will become calculating a collision normal, in what direction should that be if they are exactly overlapping?

**Comment by torkleyy** [comment]
I think there should be simply no collision, but also no panic.

**Comment by Rhuagh** [comment]
Not sure that's the best idea. This would also occur for two different shapes that are exactly overlapping.

**Comment by Rhuagh** [comment]
So, I checked into it now, and the basic issue for exactly overlapping shapes, is that all support points become the origin.

**Comment by Rhuagh** [comment]
Which makes sense when you realise that a support point is the point in a direction on one shape - the point in the same direction on the other shape, which will always be the same point of they are exactly overlapping.

**Comment by Rhuagh** [comment]
Ok, so the basic issue is that the search direction used for calculating the support points become degenerate (zero vector), because the lines between the points pass through the origin.

**Comment by Rhuagh** [comment]
So, the good news is that i've fixed the discrete tests. The bad news is that the continuous tests now fail.

**Comment by Rhuagh** [comment]
So, you will now get a collision from exact overlaps, the collision normal is degenerate though, it can point in any direction. Some more care when applying the contact resolution should fix this. 

And tbh, I don't see this scenario occur in the wild very often.
